export type ConditionGroup = {
  label: string;
  bg: string;
  text: string;
  conditions: string[];
};

export const CONDITION_GROUPS: ConditionGroup[] = [
  {
    label: "Oncology",
    bg: "#fecdd3",
    text: "#9f1239",
    conditions: [
      "Brain Tumour",
      "Breast Cancer",
      "Carcinoid Syndrome",
      "Cervical Cancer",
      "Chronic Lymphocytic Leukaemia",
      "Chronic Myeloid Leukaemia",
      "Colon Cancer",
      "Hodgkin's Lymphoma",
      "Langerhans Cell Histiocytosis",
      "Leukaemia",
      "Lung Cancer",
      "Lynch Syndrome",
      "Melanoma",
      "Mesothelioma",
      "Multiple Myeloma",
      "Myelodysplastic Syndrome",
      "Non-Hodgkin's Lymphoma",
      "Ovarian Cancer",
      "Prostate Cancer",
      "Thyroid Cancer",
      "Uterine Cancer",
      "Waldenstrom's Macroglobulinaemia",
    ],
  },
  {
    label: "Cardiology & Vascular",
    bg: "#dbeafe",
    text: "#1d4ed8",
    conditions: [
      "Aortic Stenosis",
      "Atrial Fibrillation",
      "Coronary Artery Disease",
      "Deep Vein Thrombosis",
      "Heart Failure",
      "Hypertension",
      "Hypertrophic Cardiomyopathy",
      "Pulmonary Hypertension",
      "Stroke",
    ],
  },
  {
    label: "Neurology & Mental Health",
    bg: "#ede9fe",
    text: "#6d28d9",
    conditions: [
      "ADHD",
      "Alexia",
      "ALS (Amyotrophic Lateral Sclerosis)",
      "Alzheimer's Disease",
      "Anxiety Disorder",
      "Ataxia",
      "Autism Spectrum Disorder",
      "Bipolar Disorder",
      "Charcot-Marie-Tooth Disease",
      "Dementia",
      "Depression",
      "Epilepsy",
      "Hereditary Spastic Paraplegia",
      "Huntington's Disease",
      "Hydrocephalus",
      "Migraine",
      "Multiple Sclerosis",
      "Muscular Dystrophy",
      "Myasthenia Gravis",
      "Narcolepsy",
      "Parkinson's Disease",
      "Peripheral Neuropathy",
      "Spinal Muscular Atrophy",
      "Stiff Person Syndrome",
      "Tourette Syndrome",
      "Transverse Myelitis",
      "Vertigo",
    ],
  },
  {
    label: "Gastroenterology & Hepatology",
    bg: "#fef3c7",
    text: "#d97706",
    conditions: [
      "Autoimmune Hepatitis",
      "Celiac Disease",
      "Cirrhosis",
      "Crohn's Disease",
      "Eosinophilic Oesophagitis",
      "Familial Adenomatous Polyposis (FAP)",
      "Gallstones",
      "GERD",
      "Inflammatory Bowel Disease",
      "Irritable Bowel Syndrome",
      "Liver Disease",
      "Pancreatitis",
      "Peutz-Jeghers Syndrome",
      "Primary Biliary Cholangitis",
      "Primary Sclerosing Cholangitis",
      "Ulcerative Colitis",
    ],
  },
  {
    label: "Rheumatology & Autoimmune",
    bg: "#ccfbf1",
    text: "#0f766e",
    conditions: [
      "Ankylosing Spondylitis",
      "Antiphospholipid Syndrome",
      "Arthritis",
      "Behçet's Disease",
      "Dermatomyositis",
      "Fibromyalgia",
      "Goodpasture Syndrome",
      "Gout",
      "Lupus",
      "Polymyalgia Rheumatica",
      "Psoriatic Arthritis",
      "Rheumatoid Arthritis",
      "Sarcoidosis",
      "Scleroderma",
      "Sjögren's Syndrome",
      "Vasculitis",
    ],
  },
  {
    label: "Endocrinology & Metabolism",
    bg: "#e0e7ff",
    text: "#4338ca",
    conditions: [
      "Adrenal Insufficiency",
      "Cushing's Syndrome",
      "Diabetes Type 1",
      "Diabetes Type 2",
      "Familial Hypercholesterolaemia",
      "High Cholesterol",
      "Hyperthyroidism",
      "Hypothyroidism",
      "Obesity",
      "Polycystic Ovary Syndrome",
    ],
  },
  {
    label: "Pulmonology & Respiratory",
    bg: "#e0f2fe",
    text: "#0369a1",
    conditions: [
      "Asthma",
      "COPD",
      "Cystic Fibrosis",
      "Long COVID",
      "Pulmonary Fibrosis",
      "Sleep Apnea",
    ],
  },
  {
    label: "Haematology",
    bg: "#fee2e2",
    text: "#b91c1c",
    conditions: [
      "Anaemia",
      "Cryoglobulinemia",
      "Haemochromatosis",
      "Haemophilia",
      "Sickle Cell Disease",
      "Von Willebrand Disease",
    ],
  },
  {
    label: "Nephrology & Urology",
    bg: "#cffafe",
    text: "#0e7490",
    conditions: [
      "Alport Syndrome",
      "Chronic Kidney Disease",
      "IgA Nephropathy",
      "Interstitial Cystitis",
      "Kidney Stones",
      "Polycystic Kidney Disease",
    ],
  },
  {
    label: "Musculoskeletal & Bone",
    bg: "#f5f5f4",
    text: "#57534e",
    conditions: [
      "Ehlers-Danlos Syndrome",
      "Marfan Syndrome",
      "Osteogenesis Imperfecta",
      "Osteoarthritis",
      "Osteoporosis",
    ],
  },
  {
    label: "Dermatology",
    bg: "#fce7f3",
    text: "#9d174d",
    conditions: [
      "Acne",
      "Eczema",
      "Ichthyosis",
      "Pemphigus Vulgaris",
      "Psoriasis",
      "Sweet's Syndrome",
      "Vitiligo",
    ],
  },
  {
    label: "Women's Health",
    bg: "#fdf4ff",
    text: "#86198f",
    conditions: [
      "Endometriosis",
      "Uterine Fibroids",
    ],
  },
  {
    label: "Infectious Disease",
    bg: "#d1fae5",
    text: "#065f46",
    conditions: [
      "Hepatitis B",
      "Hepatitis C",
      "HIV/AIDS",
      "Lyme Disease",
    ],
  },
  {
    label: "Ophthalmology",
    bg: "#f3f0ff",
    text: "#4c1d95",
    conditions: [
      "Glaucoma",
      "Macular Degeneration",
    ],
  },
  {
    label: "Rare & Genetic",
    bg: "#f3f4f6",
    text: "#374151",
    conditions: [
      "Alagille Syndrome",
      "Albinism",
      "Angelman Syndrome",
      "Castleman Disease",
      "Down Syndrome",
      "Fabry Disease",
      "Familial Mediterranean Fever",
      "Gaucher Disease",
      "Hereditary Haemorrhagic Telangiectasia",
      "Mastocytosis",
      "Mitochondrial Disease",
      "Neurofibromatosis",
      "Niemann-Pick Disease",
      "Phenylketonuria (PKU)",
      "Pompe Disease",
      "Primary Immunodeficiency",
      "Rare Chromosome Disorder",
      "Systemic Mastocytosis",
      "Tay-Sachs Disease",
      "Tuberous Sclerosis",
      "von Hippel-Lindau Disease",
      "Wilson's Disease",
      "Wolfram Syndrome",
    ],
  },
  {
    label: "Other",
    bg: "#fafaf9",
    text: "#78716c",
    conditions: [
      "Chronic Fatigue Syndrome",
      "Chronic Pain",
      "Meniere's Disease",
    ],
  },
];

// Derived alphabetically-sorted flat list used by ConditionSelector and elsewhere
export const CONDITIONS: string[] = CONDITION_GROUPS
  .flatMap((g) => g.conditions)
  .sort((a, b) => a.localeCompare(b));

// Lookup: condition name → its group
export const CONDITION_TO_GROUP: Record<string, ConditionGroup> = Object.fromEntries(
  CONDITION_GROUPS.flatMap((g) => g.conditions.map((c) => [c, g]))
);
